.\" Man page for lab05 piglatin
.\" Adam Cooper and Helen Stern - Spring 2017

.TH pig_man 7 "31 March 2017" "CSCI 241" "Oberlin College"

.SH NAME
.B pig
\- translates to piglatin

.SH SYNOPSIS
.B pig
[ -h -? ]
[ < inputfile ]

.SH DESCRIPTION
Translates a whole file into piglatin

.SH OPTIONS
.IP "-h"
Help
.IP "-?"
Help

.SH AUTHORS
    Adam Cooper and Helen Stern (Spring 2017)

.SH BUGS
None!
