.\" Man page for lab05 unpig
.\" Adam Cooper and Helen Stern

.TH unpig_man 7 "31 March 2017" "CSCI 241" "Oberlin College"

.SH NAME
.B unpig
[ -h -? ]
[ < inputfile ] 

.SH DESCRIPTION
Translates a whole file from piglatin

.SH OPTIONS
.IP "-h"
Help
.IP "-?"
Help

.SH AUTHORS
    Adam Cooper and Helen Stern (Spring 2017)

.SH BUGS
It's full of features
