.\"
    Man page for Huffman Tree decodeing program "decode"

.TH decode_man 1 "30 April 2017" "CSCI 241" "Oberlin College"

.SH NAME
.B decode <file>
\- decodes a file that has been previously compressed using ./encode

.SH SYNOPSIS
.B ./decode

.SH DESCRIPTION
Decompresses a file that has previously been compressed using the Huffman Tree compression program "encode", and then outputs the decompressed file to stdout

.SH OPTIONS
.IP "<file>" 
The file to decode

.SH AUTHORS
Adam Cooper and Helen Stern

.SH BUGS
None that we know of
