.\" Man page for lab06 string sort
.\" Adam Cooper and Helen Stern

.TH sort_man 1 "11 April 2017" "CSCI 241" "Oberlin College"

.SH NAME
.B sort
\- sorts strings

.SH SYNOPSIS
.B sort
[ -f -n -h -? ]
[ < inputfile ]

.SH DESCRIPTION
Sorts strings

.SH OPTIONS
.IP "-f"
Fold (ignore) case
.IP "-n"
Sort by leading number ignoring leading space
.SP "-h"
Help
.SP "-?"
Help

.SH AUTHORS
    Adam Cooper and Helen Stern (Spring 2017)

.SH BUGS
    None we know of...
